apiVersion: apps/v1
kind: Deployment
metadata:
  name: dropbear
  namespace: default
  labels:
    app: dropbear
  # annotations:
  #   fluxcd.io/ignore: true
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dropbear
  template:
    metadata:
      labels:
        app: dropbear
        regist-jumpserver/enabled: enabled
    spec:
      #imagePullSecrets:
      #- name: regsecret
      containers:
      - name: test
        image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/alpine-ext:weak
        imagePullPolicy: Always      
        # command: ['sh', '-c'] #use Dockerfile's entrypoint
        args:
        - tail -f /dev/null
        env:
          - name: SSHD_ENABLE
            value: "true"
        ports:
        - containerPort: 22    
      restartPolicy: Always
