---
apiVersion: v1
kind: Service
metadata:
  name: kubecmd-svc
  namespace: kube-system
  labels:
    app: kubecmd-svc
spec:
  ports:
    - port: 22
      name: ssh
      targetPort: 22
  selector:
    app: "kubecmd"
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecmd
  namespace: kube-system
  labels:
    app: kubecmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecmd
  template:
    metadata:
      labels:
        app: kubecmd
        regist-jumpserver/enabled: enabled
    spec:
      containers:
      - name: kubecmd
        image: registry.cn-shenzhen.aliyuncs.com/infrastlabs/kube-cmd
        imagePullPolicy: Always      
        # command: ['sh', '-c']
        # args:
        # - tail -f /dev/null
        env:
          - name: SSHD_ENABLE
            value: "true"        
        ports:
        - containerPort: 22
      restartPolicy: Always
