apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: kube-system
resources:
  - dp-dropbear.yml
  - dp-jumpserver.yml
  - dp-kube-cmd.yml
  - jumpregister-all.yml
  
bases:
  # - ./src
patchesStrategicMerge:
  # - patch.yml
